version: '3.8'
services:
  app:
    image: 'lorisleiva/laravel-docker:8.2'
    container_name: chandra-asri-cms-app
    ports:
      - '8000:8000'
    tty: true
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=chandra_asri_cms
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
    networks:
      - chandra-asri-network

  db:
    image: 'mysql:8.0'
    container_name: chandra-asri-cms-db
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=chandra_asri_cms
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - chandra-asri-network

  adminer:
    image: adminer
    container_name: chandra-asri-cms-adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - chandra-asri-network
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: chandra-asri-cms-redis
    ports:
      - 6379:6379
    networks:
      - chandra-asri-network

networks:
  chandra-asri-network:
    driver: bridge

volumes:
  dbdata:
