@inject('model', '\App\Domains\Post\Models\Post')
@extends('backend.layouts.app')
@section('title', 'Create Page - ' . $template['label'])
@section('content')
    <x-forms.post :action="route('admin.page.store', ['type' => 'page', 'template' => $template['name']])" enctype="multipart/form-data">
        <x-backend.card>
            <x-slot name="header">
                @lang('Create Page')
            </x-slot>

            <x-slot name="headerActions">
                <x-utils.link class="card-header-action" :href="route('admin.page')" :text="__('Cancel')" />
            </x-slot>

            <x-slot name="body">
                <x-forms.text-input name="title" label="Title" required="1" placeholder="The title of page"
                    text="A page name is required and recommended to be unique." />

                {{-- <x-forms.text-input name="slug" label="Slug" placeholder="The slug of page" --}}
                {{-- text="The slug is recommended to be unique & can also nullable and will auto generated by title of the page" disabled="1"/> --}}
                <div class="d-flex gap-4">
                    <div class="flex-fill">
                        <div class="mb-8 fv-row fv-plugins-icon-container">
                            <label for="status" class="form-label">@lang('Post Status')</label>
                            <select name="status" class="form-control mb-2" required="" id="status">
                                <option value="{{ $model::STATUS_PUBLISH }}">@lang('Publish')</option>
                                <option value="{{ $model::STATUS_SCHEDULE }}">@lang('Schedule')</option>
                                <option value="{{ $model::STATUS_DRAFT }}">@lang('Draft')</option>
                            </select>
                        </div>
                    </div>
                    <div class="flex-fill" id="divPublishAt">
                        <div class="mb-8 fv-row fv-plugins-icon-container">
                            <label class="form-label">Schedule At</label>
                            <input type="datetime-local" name="published_at" id="published_at" value=""
                                class="form-control mb-2" placeholder="{{ __('Publish time') }}" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    @if ($parents->count() > 0)
                        <div class="col-md-12">
                            <div class="mb-8 fv-row fv-plugins-icon-container">
                                <label for="status" class="form-label">@lang('Parent')</label>
                                <select name="parent" class="form-select form-select-solid mb-2" id="parent">
                                    <option value="" selected>-- None --</option>
                                    @foreach ($parents as $key => $item)
                                        <option value="{{ $item }}">{{ $key }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    @endif
                </div>
                @if (count($components) > 0)
                    <div class="card card-flush p-3 mt-8">
                        <div class="card-body p-3">
                            <div id="app">
                                @if (!isset($template['multilanguage']))
                                    @php $template['multilanguage'] = 'false' @endphp
                                @endif
                                @if ($template['multilanguage'] === 'true')
                                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                                        @foreach ($template['lang_option'] as $lang)
                                            @php
                                                $lang_title = $lang['name'];
                                                $lang_code = $lang['value'];
                                            @endphp
                                            <li class="nav-item" role="presentation">
                                                <button class="nav-link @if ($loop->first) active @endif"
                                                    id="{{ $lang_code }}-tab" data-bs-toggle="tab"
                                                    data-bs-target="#{{ $lang_code }}" type="button" role="tab"
                                                    aria-controls="{{ $lang_code }}" aria-selected="true">
                                                    {{ strtoupper($lang_title) }}
                                                </button>
                                            </li>
                                        @endforeach
                                    </ul>
                                    <div class="tab-content" id="myTabContent">
                                        @foreach ($template['lang_option'] as $lang)
                                            @php
                                                $lang_title = $lang['name'];
                                                $lang_code = $lang['value'];
                                            @endphp
                                            <div class="tab-pane fade @if ($loop->first) show active @endif"
                                                id="{{ $lang_code }}" role="tabpanel"
                                                aria-labelledby="{{ $lang_code }}-tab">
                                                @foreach ($components as $component)
                                                    @include('components.backend.component-wrapper-v2', [
                                                        'component' => $component,
                                                        'loopIndex' => $loop->index,
                                                        'postId' => $post->id,
                                                        'lang' => $lang_code,
                                                        'lang_option' => $template['lang_option'],
                                                    ])
                                                @endforeach
                                            </div>
                                        @endforeach
                                    </div>
                                @else
                                    @foreach ($components as $component)
                                        @include('components.backend.component-wrapper-v2', [
                                            'component' => $component,
                                            'loopIndex' => $loop->index,
                                            'postId' => $post->id,
                                        ])
                                    @endforeach
                                @endif
                            </div>
                        </div>
                    </div>
                @else
                    <x-forms.ckeditor5-editor name="content" label="Content" required="0" />
                    <x-forms.text-input name="meta_title" label="Meta Title" required="0" value="" maxlength="60"
                        placeholder="" text="The ideal length of meta title is about 60 characters" />
                    <x-forms.text-input name="meta_keyword" label="Meta Keyword" required="0" value=""
                        placeholder="" text="" />
                    <x-forms.textarea-input name="meta_description" label="Meta Description" value="" required="0"
                        placeholder="" maxlength="165" text="Meta descriptions at around 160-165 characters" />
                    <x-forms.textarea-input name="excerpt" label="Excerpt" required="1" placeholder="Summary of post"
                        text="" value="" />
                @endif
                <button class="btn btn-primary">Create Page</button>
            </x-slot>
        </x-backend.card>

    </x-forms.post>
@endsection


@push('scripts')
    <script>
        $('#divPublishAt').hide();
        $('#status').change(function() {
            if ($('#status').val() == 'schedule') {
                $('#divPublishAt').show();
                $('#published_at').prop('required', true);
                $('#btnSubmit').html('Save & Schedule')
            } else {
                $('#divPublishAt').hide();
                $('#published_at').prop('required', false);

                if ($('#status').val() == 'publish') {
                    $('#btnSubmit').html('Save & Publish')
                } else {
                    $('#btnSubmit').html('Save Draft')
                }

            }
        });
    </script>
@endpush
