@inject('model', '\App\Domains\Post\Models\Post')
@extends('backend.layouts.app')
@section('title', 'Edit Page - ' . $template['label'])
@section('content')
    <x-forms.post :action="route('admin.page.update', ['type' => 'page', 'template' => $template['name'], 'post' => $post])" enctype="multipart/form-data">
        @method('PATCH')
        <x-backend.card>
            <x-slot name="header">
                @lang('Edit Page')
            </x-slot>

            <x-slot name="headerActions">
                <x-utils.link class="card-header-action" :href="route('admin.page')" :text="__('Cancel')" />
            </x-slot>

            <x-slot name="body">

                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif
                <x-forms.text-input name="title" label="Title" required="1" value="{{ $post->title }}"
                    placeholder="The title of page" text="A page name is required and recommended to be unique." />
                {{-- <x-forms.text-input name="slug" label="Slug" placeholder="The slug of page" value="{{ $post->slug }}" --}}
                    {{-- text="The slug is recommended to be unique & can also nullable and will auto generated by title of the page"  disabled="1" hidden="1"/> --}}
                {{-- <x-forms.text-input name="site_url" label="Site URL" placeholder="" text="The site path url of page" value="{{ $post->site_url ?? $template['slug'] }}" --}}
                    {{-- text=""  disabled="1"/> --}}
                <div class="d-flex gap-4">
                    <div class="flex-fill">
                        <div class="mb-8 fv-row fv-plugins-icon-container">
                            <label for="status" class="form-label">@lang('Post Status')</label>
                            <select name="status" class="form-control form-control-solid mb-2" required=""
                                id="status">
                                <option value="{{ $model::STATUS_PUBLISH }}"
                                    {{ $post->status === $model::STATUS_PUBLISH ? 'selected' : '' }}>@lang('Publish')
                                </option>
                                <option value="{{ $model::STATUS_SCHEDULE }}"
                                    {{ $post->status === $model::STATUS_SCHEDULE ? 'selected' : '' }}>@lang('Schedule')
                                </option>
                                <option value="{{ $model::STATUS_DRAFT }}"
                                    {{ $post->status === $model::STATUS_DRAFT ? 'selected' : '' }}>@lang('Draft')
                                </option>
                            </select>
                        </div>
                    </div>
                    <div class="flex-fill" id="divPublishAt">
                        <div class="mb-8 fv-row fv-plugins-icon-container">
                            <label class="form-label">Schedule At</label>
                            <input type="datetime-local" name="published_at" id="published_at" value="@displayDate($post->published_at, 'Y-m-d\TH:i')"
                                class="form-control form-control-solid mb-2" placeholder="{{ __('Publish time') }}" />
                        </div>
                    </div>
                </div>


                <div class="row">
                    @if ($parents->count() > 0)
                        <div class="col-md-12">
                            <div class="mb-8 fv-row fv-plugins-icon-container">
                                <label for="status" class="form-label">@lang('Parent')</label>
                                <select name="parent" class="form-select form-select-solid mb-2" id="parent">
                                    @if ($post->parent != null)
                                        <option value="">-- None --</option>
                                        @foreach ($parents as $key => $item)
                                            <option value="{{ $item }}"
                                                {{ $post->parent == $item ? 'selected' : '' }}>{{ $key }}</option>
                                        @endforeach
                                    @else
                                        <option value="" selected>-- None --</option>
                                        @foreach ($parents as $key => $item)
                                            <option value="{{ $item }}"
                                                {{ $post->parent == $item ? 'selected' : '' }}>{{ $key }}
                                            </option>
                                        @endforeach
                                    @endif
                                </select>
                            </div>
                        </div>
                    @endif
                </div>
                @if (count($components) > 0)
                    <div class="card card-flush p-3 mt-8">
                        <div class="card-body p-3">
                            <div id="app">
                                @if (!isset($template['multilanguage']))
                                    @php $template['multilanguage'] = 'false' @endphp
                                @endif
                                @if ($template['multilanguage'] === 'true')
                                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                                        @foreach ($template['lang_option'] as $lang)
                                            @php
                                                $lang_title = $lang['name'];
                                                $lang_code = $lang['value'];
                                            @endphp
                                            <li class="nav-item" role="presentation">
                                                <button class="nav-link @if ($loop->first) active @endif"
                                                    id="{{ $lang_code }}-tab" data-bs-toggle="tab"
                                                    data-bs-target="#{{ $lang_code }}" type="button" role="tab"
                                                    aria-controls="{{ $lang_code }}" aria-selected="true">
                                                    {{ strtoupper($lang_title) }}
                                                </button>
                                            </li>
                                        @endforeach
                                    </ul>
                                    <div class="tab-content" id="myTabContent">
                                        @foreach ($template['lang_option'] as $lang)
                                            @php
                                                $lang_title = $lang['name'];
                                                $lang_code = $lang['value'];
                                            @endphp
                                            <div class="tab-pane fade @if ($loop->first) show active @endif"
                                                id="{{ $lang_code }}" role="tabpanel"
                                                aria-labelledby="{{ $lang_code }}-tab">
                                                @foreach ($components as $component)
                                                    @include('components.backend.component-wrapper-v2', [
                                                        'component' => $component,
                                                        'loopIndex' => $loop->index,
                                                        'postId' => $post->id,
                                                        'lang' => $lang_code,
                                                        'lang_option' => $template['lang_option'],
                                                    ])

                                                    @php
                                                        $bannerMap = [
                                                            'financial_report' => 'financial-reports',
                                                            'financial_reports' => 'financial-reports',
                                                            'business_solution' => 'journey-growth',
                                                        ];
                                                        $pos = $bannerMap[$component['keyName']] ?? null;
                                                    @endphp

                                                    @if ($pos && ($post->slug == 'home' || $post->site_url == '/'))
                                                        @php
                                                            $active = isset($homeBanners[$pos]) ? $homeBanners[$pos]->where('language', $lang_code)->first() : null;
                                                        @endphp
                                                        <div class="form-group row border-top pt-5 mt-5 {{ $pos }}-banner-config">
                                                            <label class="col-md-2 col-form-label fw-bold text-capitalize">
                                                                Banner {{ str_replace('-', ' ', $pos) }}
                                                            </label>
                                                            <div class="col-md-10">
                                                                <div class="row">
                                                                    <div class="col-md-4">
                                                                        <label class="form-label">Banner Group</label>
                                                                        <select name="home_banners[{{ $lang_code }}][{{ $pos }}][banner_group_id]"
                                                                            class="form-select form-select-solid">
                                                                            <option value="">-- Select Banner Group --</option>
                                                                            @foreach ($bannerGroups as $bg)
                                                                                <option value="{{ $bg->id }}"
                                                                                    {{ optional($active)->banner_group_id == $bg->id ? 'selected' : '' }}>
                                                                                    {{ $bg->title }}
                                                                                </option>
                                                                            @endforeach
                                                                        </select>
                                                                    </div>
                                                                    <div class="col-md-4">
                                                                        <label class="form-label">Start Date</label>
                                                                        <input type="datetime-local"
                                                                            name="home_banners[{{ $lang_code }}][{{ $pos }}][start_date]"
                                                                            class="form-control form-control-solid"
                                                                            value="{{ $active && $active->start_date ? $active->start_date->format('Y-m-d\TH:i') : '' }}">
                                                                    </div>
                                                                    <div class="col-md-4">
                                                                        <label class="form-label">End Date</label>
                                                                        <input type="datetime-local"
                                                                            name="home_banners[{{ $lang_code }}][{{ $pos }}][end_date]"
                                                                            class="form-control form-control-solid"
                                                                            value="{{ $active && $active->end_date ? $active->end_date->format('Y-m-d\TH:i') : '' }}">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    @endif
                                                @endforeach
                                            </div>
                                        @endforeach
                                    </div>
                                @else
                                    @foreach ($components as $component)
                                        @include('components.backend.component-wrapper-v2', [
                                            'component' => $component,
                                            'loopIndex' => $loop->index,
                                            'postId' => $post->id,
                                        ])

                                        @php
                                            $bannerMap = [
                                                'financial_report' => 'financial-reports',
                                                'financial_reports' => 'financial-reports',
                                                'business_solution' => 'journey-growth',
                                            ];
                                            $pos = $bannerMap[$component['keyName']] ?? null;
                                        @endphp

                                        @if ($pos && ($post->slug == 'home' || $post->site_url == '/'))
                                            @php
                                                $active = isset($homeBanners[$pos]) ? $homeBanners[$pos]->where('language', 'id')->first() : null;
                                            @endphp
                                            <div class="form-group row border-top pt-5 mt-5 {{ $pos }}-banner-config">
                                                <label class="col-md-2 col-form-label fw-bold text-capitalize">
                                                    Banner {{ str_replace('-', ' ', $pos) }}
                                                </label>
                                                <div class="col-md-10">
                                                    <div class="row">
                                                        <div class="col-md-4">
                                                            <label class="form-label">Banner Group</label>
                                                            <select name="home_banners[id][{{ $pos }}][banner_group_id]"
                                                                class="form-select form-select-solid">
                                                                <option value="">-- Select Banner Group --</option>
                                                                @foreach ($bannerGroups as $bg)
                                                                    <option value="{{ $bg->id }}"
                                                                        {{ optional($active)->banner_group_id == $bg->id ? 'selected' : '' }}>
                                                                        {{ $bg->title }}
                                                                    </option>
                                                                @endforeach
                                                            </select>
                                                        </div>
                                                        <div class="col-md-4">
                                                            <label class="form-label">Start Date</label>
                                                            <input type="datetime-local"
                                                                name="home_banners[id][{{ $pos }}][start_date]"
                                                                class="form-control form-control-solid"
                                                                value="{{ $active && $active->start_date ? $active->start_date->format('Y-m-d\TH:i') : '' }}">
                                                        </div>
                                                        <div class="col-md-4">
                                                            <label class="form-label">End Date</label>
                                                            <input type="datetime-local"
                                                                name="home_banners[id][{{ $pos }}][end_date]"
                                                                class="form-control form-control-solid"
                                                                value="{{ $active && $active->end_date ? $active->end_date->format('Y-m-d\TH:i') : '' }}">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        @endif
                                    @endforeach
                                @endif
                            </div>
                        </div>
                    </div>
                @else
                    <x-forms.ckeditor5-editor name="content" label="Content" required="0" value="{{ $post->content }}" />
                    <x-forms.text-input name="meta_title" label="Meta Title" required="0" value="{{ $post->meta_title }}"
                        maxlength="60" placeholder="" text="The ideal length of meta title is about 60 characters" />
                    <x-forms.text-input name="meta_keyword" label="Meta Keyword" required="0"
                        value="{{ $post->meta_keyword }}" placeholder="" text="" />
                    <x-forms.textarea-input name="meta_description" label="Meta Description"
                        value="{{ $post->meta_description }}" required="0" placeholder="" maxlength="165"
                        text="Meta descriptions at around 160-165 characters" />
                    <x-forms.textarea-input name="excerpt" label="Excerpt" required="1" placeholder="Summary of post"
                        text="" value="{{ $post->excerpt }}" />
                @endif
                
                <button class="btn btn-primary" id="btnSubmit">Update Page</button>
            </x-slot>
        </x-backend.card>

    </x-forms.post>
@endsection

@push('scripts')
    <script>
        $('#divPublishAt').hide();
        $('#status').change(function() {
            if ($('#status').val() == 'schedule') {
                $('#divPublishAt').show();
                $('#published_at').prop('required', true);
                $('#btnSubmit').html('Update & Schedule')
            } else {
                $('#divPublishAt').hide();
                $('#published_at').prop('required', false);

                if ($('#status').val() == 'publish') {
                    $('#btnSubmit').html('Update Post')
                } else {
                    $('#btnSubmit').html('Update Draft')
                }

            }
        });

        @if ($post->status === $model::STATUS_SCHEDULE)
            $('#divPublishAt').show();
        @endif
    </script>
@endpush
